name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            artifact_name: peek_tree-linux
          - os: macos-latest
            artifact_name: peek_tree-macos

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git

      - name: Update Version in Header File
        run: |
          VERSION_TAG=${GITHUB_REF#refs/tags/}
          sed -i.bak "s|#define VERSION.*|#define VERSION \"$VERSION_TAG\"|" ./src/peek_tree.h
          git add ./src/peek_tree.h
          git commit -m "Update version to $VERSION_TAG"
          git push 

      - name: Build
        run: make -C ./src

      - name: Create Release Asset
        run: tar czf ${{ matrix.artifact_name }}.tar.gz -C ./src peek_tree

      - name: Create and Upload Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.artifact_name }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Update Homebrew Formula
        if: matrix.os == 'macos-latest'
        run: |
          sed -i.bak "s|url.*|url \"https://github.com/${{ github.repository }}/releases/download/${{ github.ref }}/peek_tree-macos.tar.gz\"|" ./dist/Homebrew/peek_tree.rb
          sed -i.bak "s|sha256.*|sha256 \"$(shasum -a 256 ./peek_tree-macos.tar.gz | awk '{ print $1 }')\"|" ./dist/Homebrew/peek_tree.rb
          git add ./dist/Homebrew/peek_tree.rb
          git commit -m "Update Homebrew formula for $VERSION_TAG"
          git push
