name: Release

on:
  push:
    tags:
        - 'v*'


permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            artifact_name: peek_tree-linux
          - os: macos-latest
            artifact_name: peek_tree-macos

    steps:
      - uses: actions/checkout@v2

      - name: Update Version in Header File
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          VERSION_TAG=${{ github.ref_name }}
          sed -i.bak "s|#define VERSION.*|#define VERSION \"$VERSION_TAG\"|" ./src/peek_tree.h
          rm -rf ./src/peek_tree.h.bak

      - name: Commit Version Update
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git fetch origin main:main
          git checkout main
          git add ./src/peek_tree.h
          git commit -m "Update version to ${{ github.ref_name }}"
          git push origin main

      - name: Build
        run: make -C peek_tree/src

      - name: Create Release Asset
        run: |
          tar czf ${{ matrix.artifact_name }}.tar.gz -C peek_tree/src peek_tree

      - name: Upload Release Asset
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_name }}.tar.gz

      - name: Calculate SHA256 Checksum
        if: matrix.os == 'macos-latest'
        id: checksum
        run: echo "sha256=$(shasum -a 256 ${{ matrix.artifact_name }}.tar.gz | awk '{ print $1 }')" >> $GITHUB_OUTPUT

    outputs:
      sha256: ${{ steps.checksum.outputs.sha256 }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./peek_tree-linux/peek_tree-linux.tar.gz
          asset_name: peek_tree-linux.tar.gz
          asset_content_type: application/gzip

      - name: Update Homebrew Formula
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git checkout main
          sed -i.bak "s|url.*|url \"https://github.com/aymanhki/peek_tree/releases/download/${{ github.ref_name }}/peek_tree-macos.tar.gz\"|" ./dist/Homebrew/peek_tree.rb
          sed -i.bak "s|sha256.*|sha256 \"${{ needs.build.outputs.sha256 }}\"|" ./dist/Homebrew/peek_tree.rb
          git fetch origin main:main
          git checkout main
          git add ./dist/Homebrew/peek_tree.rb
          git commit -m "Update Homebrew formula for ${{ github.ref_name }}"
          git push origin main






