name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git and Update Version
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git fetch --all
          git checkout main
          VERSION_TAG=${GITHUB_REF#refs/tags/}
          sed -i.bak "s|#define VERSION.*|#define VERSION \"$VERSION_TAG\"|" ./src/peek_tree.h
          git add ./src/peek_tree.h
          git commit -m "Update version to $VERSION_TAG"
          git push origin main

  build-and-release:
    needs: update-version
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            artifact_name: peek_tree-linux
            platform: linux
          - os: macos-latest
            artifact_name: peek_tree-macos
            platform: macos

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Install Build Dependencies (Linux)
        if: matrix.platform == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y clang

      - name: Build
        run: |
          cd ./src
          make clean
          make
          file peek_tree

      - name: Create Release Asset
        run: tar czf ${{ matrix.artifact_name }}.tar.gz -C ./src peek_tree

      - name: Calculate SHA256 Checksum
        if: matrix.platform == 'macos'
        id: checksum
        run: echo "::set-output name=sha256::$(shasum -a 256 ${{ matrix.artifact_name }}.tar.gz | awk '{ print $1 }')"

      - name: Update Homebrew Formula
        if: matrix.platform == 'macos'
        run: |
          git fetch --all
          git checkout main
          VERSION_TAG=${GITHUB_REF#refs/tags/}
          sed -i.bak "s|url.*|url \"https://github.com/${{ github.repository }}/releases/download/$VERSION_TAG/${{ matrix.artifact_name }}.tar.gz\"|" ./dist/Homebrew/peek_tree.rb
          sed -i.bak "s|sha256.*|sha256 \"${{ steps.checksum.outputs.sha256 }}\"|" ./dist/Homebrew/peek_tree.rb
          git add ./dist/Homebrew/peek_tree.rb
          git commit -m "Update Homebrew formula for $VERSION_TAG"
          git push origin main

      - name: Create and Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.artifact_name }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}